// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHe6x9k9GnkGGTnYjub_8AOzvYSe9YJzw',
    appId: '1:44878482172:web:3cebb7fed1197dc6b2a579',
    messagingSenderId: '44878482172',
    projectId: 'calendario-prestadores',
    authDomain: 'calendario-prestadores.firebaseapp.com',
    storageBucket: 'calendario-prestadores.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiAI9beGEkBj-31L9Ne4MPFf5prmTeCZA',
    appId: '1:44878482172:android:5c1b3492a9002422b2a579',
    messagingSenderId: '44878482172',
    projectId: 'calendario-prestadores',
    storageBucket: 'calendario-prestadores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxBACrP0KclujOY4JY28YbTVsrV6oBm3M',
    appId: '1:44878482172:ios:cdd43636b775c685b2a579',
    messagingSenderId: '44878482172',
    projectId: 'calendario-prestadores',
    storageBucket: 'calendario-prestadores.firebasestorage.app',
    iosBundleId: 'br.com.felipearaujo.diarias',
  );
}
